### ISSUE TITLE
imos netcdf filename checker

### ISSUE THREAD

**Issue by lbesnard** [aodn/compliance-checker#1] opened 2015-05-27 06:12 UTC
@fxmzb123 I found some issues with the new imos-file-name test

see the following two files :
- http://thredds.aodn.org.au/thredds/fileServer/IMOS/SRS/SRS-OC/SRS-OC-SOOP_Rad/VMQ9273_Solander/2014/IMOS_SRS-OC_F_20140312T030831Z_VMQ9273_FV01_DALEC_20140312T032541Z_C-20140629T231726Z.nc
- http://thredds.aodn.org.au/thredds/fileServer/IMOS/SRS/SRS-OC-BODBAW/2010_cruise-SS201009/absorption/IMOS_SRS-OC-BODBAW_X_20101016T234500Z_SS201009-absorption-CDOM_END-20110821T035100Z_C-20140401T110000Z.nc

The test fail for both files 

```
Running Compliance Checker on the dataset from: IMOS_SRS-OC_F_20140312T030831Z_VMQ9273_FV01_DALEC_20140312T032541Z_C-20140629T231726Z.nc
Traceback (most recent call last):
  File "/home/user/compliance-checker/cchecker.py", line 27, in <module>
    sys.exit(main())
  File "/home/user/compliance-checker/cchecker.py", line 21, in main
    args.criteria)
  File "/home/user/compliance-checker/compliance_checker/runner.py", line 45, in run_checker
    score_groups = cs.run(ds, ds_loc, *checker_names)
  File "/home/user/compliance-checker/compliance_checker/suite.py", line 84, in run
    dsp                = checker.load_datapair(ds, ds_loc)
  File "/home/user/compliance-checker/compliance_checker/base.py", line 78, in load_datapair
    data_object = NetCDFDogma('ds', self.beliefs(), ds, namespaces=namespaces)
  File "/usr/local/lib/python2.7/dist-packages/wicken/dogma.py", line 136, in __call__
    obj = super(MetaReligion, clsType).__call__(religion, beliefs, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wicken/netcdf_dogma.py", line 45, in __init__
    root = parse_nc_dataset_as_etree(dataObject)
  File "/usr/local/lib/python2.7/dist-packages/petulantbear/netcdf_etree.py", line 443, in parse_nc_dataset_as_etree
    dataset2ncml_buffer(dataset,output)
  File "/usr/local/lib/python2.7/dist-packages/petulantbear/netcdf2ncml.py", line 238, in dataset2ncml_buffer
    parse_att(output,(attname,dataset.getncattr(attname)), indent)
  File "/usr/local/lib/python2.7/dist-packages/petulantbear/netcdf2ncml.py", line 124, in parse_att
    attvalue=sanatize(att[1])
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 143: ordinal not in range(128)
```

This file works though :
- http://thredds.aodn.org.au/thredds/fileServer/IMOS/SOOP/SOOP-ASF/ZMFR_Tangaroa/meteorological_sst_observations/2015/IMOS_SOOP-ASF_MT_20150525T000000Z_ZMFR_FV01_C-20150526T042216Z.nc

cheers

**Comment by fxmzb123** [comment] 2015-05-28 05:55
Hi lbesnard,

This issue is caused by the files contain the non-ASCII characters in attributes. I have resolved this by
set default encoding to UTF-8. The happens for all checkers and it needs to be fixed in IOOS checker as well. I will create a separated branch and send a pull-request.

Thanks,
Ming

**Comment by danfruehauf** [comment] 2015-05-28 06:04
How about using the system's locale for that? It'd be much more accurate than hardcoding it to UTF-8.

**Comment by lbesnard** [comment] 2015-05-28 07:07
> How about using the system's locale for that? It'd be much more accurate than hardcoding it to UTF-8.

from what I understand, the issue is file based, and not env based

**Comment by danfruehauf** [comment] 2015-05-28 07:18
And do the files declare their encoding?

**Comment by fxmzb123** [comment] 2015-05-29 05:48
The default encoding for Python is ASCII, Python can get system default encoding by sys.getfilesystemencoding(), which can be further set as default in Python through:
    reload(sys)
    sys.setdefaultencoding(sys.getfilesystemencoding())

**Comment by danfruehauf** [comment] 2015-05-29 05:54
We're not quite interested in the filesystem settings, but more in either what NetCDF is publishing (if it does at all), or alternatively, use the system's locale for that.

**Comment by fxmzb123** [comment] 2015-05-29 06:14
The default encoding for netcdf-python library is ''utf-8' and this should be used, I believe.

**Comment by danfruehauf** [comment] 2015-05-29 06:16
That's fine too. It's unlikely we'll use anything other than `UTF-8` in the foreseeable future. However as best practice I think it's good if it can be overriden by environment - should it ever be required.

**Comment by mhidas** [comment] 2015-06-04 04:56
It seems this is not actually an issue with the filename checker, and the encoding problem has been reported to IOOS (https://github.com/ioos/compliance-checker/issues/108), so I think we can close this.

**Closed as completed by mhidas** 2015-06-04 04:56 UTC
